#!/bin/bash
ln -sf $HOME/.config/X/Xresources $HOME/.Xresources
ln -sf $HOME/.config/vim/vimrc $HOME/.vimrc
ln -sf $HOME/.config/X/xinitrc $HOME/.xinitrc
ln -sf $HOME/.config/oh-my-zsh $HOME/.oh-my-zsh
ln -sf $HOME/.config/oh-my-zsh/zshrc $HOME/.zshrc

